apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: avbt1yo65-go
  janus-idp.io/tekton: avbt1yo65-go
  backstage.io/kubernetes-id: avbt1yo65-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: avbt1yo65-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
