apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: avbt1yo65-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: avbt1yo65-go 
  name: avbt1yo65-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: avbt1yo65-go 
